# Generated by Django 3.2 on 2021-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('image', models.ImageField(upload_to='advertisement/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
            options={
                'db_table': 'advertisement_product',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('Cake', 'Cake'), ('Capcake', 'Capcake'), ('Chesscake', 'Chesscake'), ('Marshmello', 'Marshmello')], default='Cake', max_length=60, verbose_name='Category')),
                ('short_info', models.CharField(max_length=150, verbose_name='Short info')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
