# Generated by Django 3.2 on 2021-10-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Capcake', 'Capcake'), ('Cake', 'Cake'), ('Marshmello', 'Marshmello'), ('Chesscake', 'Chesscake')], default='Cake', max_length=60, verbose_name='Category'),
        ),
    ]
